clone_depth: 1

image: Visual Studio 2019
environment:
    matrix:
        - MINGW_VERSION: mingw64
          ARCH: x86_64
        - MINGW_VERSION: mingw32
          ARCH: i686

matrix:
    fast_finish: true

build_script:
    - cd C:\projects\gnuradio
    - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syu"
    - C:\msys64\usr\bin\bash build.sh
    - appveyor PushArtifact c:\projects\gnuradio\gnuradio-%MINGW_VERSION%-deps.txt
    - appveyor PushArtifact c:\projects\gnuradio\gnuradio-%MINGW_VERSION%.tar.xz
